spring:
  application:
    name: turboDetectAI

  datasource:
    url: jdbc:postgresql://ep-lucky-term-ap33vv4h.c-7.us-east-1.aws.neon.tech/neondb?sslmode=require
    username: neondb_owner
    password: npg_uUjZRVwG9Pc1
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect

  servlet:
    multipart:
      max-file-size: 100MB
      max-request-size: 100MB

  mail:
    host: ${SPRING_MAIL_HOST}
    port: ${SPRING_MAIL_PORT}
    username: ${SPRING_MAIL_USERNAME}
    password: ${SPRING_MAIL_PASSWORD}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
            required: true

jwt:
  secret: my-super-secret-key-my-super-secret-key-123456
  expiration: 86400000

server:
  port: ${PORT:8082}